### ISSUE TITLE
Add log module

### ISSUE THREAD

**Issue by coopernurse** [simia-tech/rust-delix#20]
It would be nice to have a leveled log library.  For the first version we could probably use something simple such as:

https://github.com/rust-lang-nursery/log

Or we could add something more flexible:

https://github.com/sfackler/log4rs

The `log` crate is configured via an environment variable, and would give us basic logging to STDOUT with the ability to specify level on a per-module basis.  This is probably sufficient initially.

**Comment by phifty** [comment]
I would vote for the first simple solution. Since we'll have metrics, I would keep the logging simple. In unix environments syslog as a destination would be usable feature too. But this should be possible with the first solution.

I would also like to give some input on log-levels: http://dave.cheney.net/2015/11/05/lets-talk-about-logging

**Comment by phifty** [comment]
I'll go ahead and add the first one.
