### ISSUE TITLE
Panic in balanced_echos_from_two_remotes test

### ISSUE THREAD

**Issue by coopernurse** [simia-tech/rust-delix#21]
When testing TravisCI 2 out of 3 builds passed.  I think this test may be non-deterministic:

```
test balanced_echos_from_two_remotes ... FAILED
failures:
---- balanced_echos_from_two_remotes stdout ----
    thread 'balanced_echos_from_two_remotes' panicked at 'attempted to divide by zero', src/transport/direct/balancer/dynamic_round_robin.rs:58
```

**Comment by coopernurse** [comment]
Similar issue in this test.  If these tests use sleep, we may be seeing a performance difference on the TravisCI VMs:

```
thread 'multiple_echos_from_remote' panicked at 'called `Result::unwrap()` on an `Err` value: ServiceDoesNotExists', ../src/libcore/result.rs:688
```

You can see the full logs here:

https://travis-ci.org/coopernurse/rust-delix/jobs/100128570

**Comment by phifty** [comment]
I think problem here comes from multiple sides.
- The tests are using a lot of sleeps in order to wait for a thing to happen. Most of the sleeps can replaced (different issue). I have a solution in mind which depends on the `metric` module - which is still in progress.
- The tests cover too much functionality. I'll try to split them into smaller ones.
- There is actually a (at least one) bug in the code ;-) More fine-graded tests will point to it.

**Comment by phifty** [comment]
The dive by zero problem should be gone now.

**Comment by phifty** [comment]
The test should pass now stable. Will close the issue.
