### ISSUE TITLE
Implement http dynamic relay module

### ISSUE THREAD

**Issue by phifty** [simia-tech/rust-delix#27]
In opposite of the `http_static` module, the list of services should be changeable at runtime. Preferable via an REST JSON API (see the Wiki).

**Comment by coopernurse** [comment]
I've updated the spec to reflect Moe's suggestion.  The register and deregister operations now expect the same JSON request payload.

https://github.com/simia-tech/rust-delix/wiki/HTTP-API--%7C-Registration

**Comment by coopernurse** [comment]
I've spent more time reading the existing code. Currently ServiceMap assumes that each local service name has one and only one handler.  I think that's fine for now.

However, it means that the service name is the key for dynamic http register and deregister operations on a given node.  If you register the same service name twice, the 2nd registration will replace the first.

This also means there's no wall between static and dynamic registrations.  If I define a "UserService" in static configuration, and then dynamically register a "UserService" on the same server, the dynamic registration will replace the static one.

I don't think this is ideal behavior, but I think we should address it separately.  My short term plan is to add dynamic service registration support, which will effectively call into the same `node.register()` method that `http_static.rs` calls.

I will probably also refactor the closure in HttpStatic.add_service that does the message deliver to the target HTTP endpoint, as that behavior is the same.  It doesn't matter if the service was statically or dynamically added.

Of course all of this assumes I can figure out enough Rust!   If I get something working I'll push an in-progress branch so that I can get some help cleaning it up before we merge it.

How does this sound?

**Comment by phifty** [comment]
> This also means there's no wall between static and dynamic registrations. If I define a "UserService" in static configuration, and then dynamically register a "UserService" on the same server, the dynamic registration will replace the static one.

My argument here was not that it's impossible, I just think it's not the best usability. If I imagine being a user of delix and set up something in the config file, I'd expect it to be there all the time. And not removed or replaced.

The other thing is the implementation. Currently, `http_static` works on the TCP level and does not interpret the HTTP request much. That way you can use delix as a distributed haproxy - which could be a very interesting use case. That would be different when a API is added.

I'm still open to the dynamic idea and I'll try to help if needed. I just think the concepts and goals are currently to different to put it in one module.

**Comment by coopernurse** [comment]
I understand your opinion about static vs dynamic.  When I dug into the implementation I found that the routing work is unrelated to the relay.  It's happening in node/servicemap.

So we would need to change that if we wanted to wall the static and dynamic implementations from each other right?

**Comment by phifty** [comment]
I don't think the routing has to changed for the dynamic module. But I could be wrong. It should be already possible to `register` a service on `Node` at runtime (and after the Node switch to the `Joined` state.

I suggest just copy the `http_static.rs` and change the `bind` method to set up some hyper server that handles the API endpoints. The `loader.rs` would have to be extended to recognise a `http_dynamic` relay type.

**Comment by phifty** [comment]
I gave it some more thoughts and might found a way to satisfy both (static and dynamic) needs. The list of local services could be stored in a JSON file which acts as a database. That way, the service list could be edited with a simple text editor and could also be changed via an API. After API calls delix could simply rewrite the JSON file. What do you think?

**Comment by phifty** [comment]
Ok, a simple API has been implemented. Docs will follow.
