### ISSUE TITLE
Global tracking of node status

### ISSUE THREAD

**Issue by moea** [simia-tech/rust-delix#8]
It'd be great to build in the ability to query the set of running nodes, their connection counts, etc. and statistics about the messages passing between them.  One piecemeal approach to this may to be to centralise logging in a object which receives event messages (however - channel, direct invocations)  from Node, Discovery, etc. and outputs them as log messages they happen, while also keeping some structured state (counts, etc.) so that it could eventually be interrogated by some administrative tool (e.g. web UI).  Let me know your thoughts.

**Comment by phifty** [comment]
I like the idea! Currently, you can already ask the Node how many connections are active, but it might be a good idea to turn this around and give the Node a metric object and let it tell about events and statistics. It might be worth using a trait here too since I could imagine different implementations (Web, StatsD, AgentX, ...). A Mutli-Implementation might be a good thing too, in order to serve multiple destinations.
